from typing import Literal

import pytorch_lightning as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
import utils.transformation_problem
import os


class SpatialTransformerClassifier(pl.LightningModule):
    """
    A classifier that applies a learned spatial transformation before classification.
    Composed of three parts:
    1. Main model (classification network)
    2. Localization network (produces features for spatial transform). Features are generated by linear map.
    3. TransformationProblem to handle the transformation process
    """
    def __init__(self,
                 main_model,
                 localization_net,
                 localization_dim,
                 transformation_problem:utils.transformation_problem.TransformationProblem,
                 train_mode: float = 0.0,
                 freeze_main=True,
                 optimizer_class=torch.optim.Adam,
                 optimizer_params={"lr": 1e-3},
                 lr_scheduler=None,
                 lr_scheduler_params=None,
                 lr_config=None,
                 pretransform=None,
                 conf_module = None,
                 l2_weight=1.0,
                 use_l2_instead_of_per_transform=True,
                 negative_sampling_module=None,
                 clamp=False,
                 use_mse = True,
                 target_param_form:Literal['matrix_inverted','matrix','params']= 'params',
                 norm_constraint_weight: float = 0.0,
                 ):
        """
        Args:
            main_model: Model for classification (can be frozen)
            localization_net: Network that outputs features for spatial transformation
            localization_dim: Dimension of localization network output
            regression_dim: Dimension of parameters to be output from regression net
            transformation_problem: TransformationProblem instance to handle transformations
            freeze_main: Whether to freeze the main model during training
            optimizer_class: Optimizer to use
            optimizer_params: Parameters for optimizer
            lr_scheduler: Optional learning rate scheduler
            lr_scheduler_params: Parameters for lr scheduler
            lr_config: Configuration for lr scheduler
            pretransform: Optional PyTorch module for pretransformation (not trained)
            train_noise_scale: Scale of noise to add to parameters during training (0.0 means no noise)
            noise_type: Type of noise to add ('gaussian' or 'uniform')
        """
        super().__init__()
        self.main_model = main_model
        self.localization_net = localization_net
        self.transformation_problem = transformation_problem
        self.pretransform = pretransform



        # Freeze main model if specified
        self.train_main = not freeze_main
        # Initialize regression network as a linear layer
        # The localization net output will be flattened before passing to this layer

        reg_dim = transformation_problem.calc_complete_size()

        self.regression_net = nn.Linear(localization_dim, reg_dim)

        # Initialize regression network with small outputs
        nn.init.normal_(self.regression_net.weight, 0, 0.01)
        nn.init.uniform_(self.regression_net.bias, -0.1, 0.1)

        # Optimizer settings
        self.optimizer_class = optimizer_class
        self.optimizer_params = optimizer_params
        self.lr_scheduler = lr_scheduler
        self.lr_scheduler_params = lr_scheduler_params
        self.lr_config = lr_config

        self.conf_module = conf_module
        self.l2_weight = l2_weight
        self.use_l2_instead_of_per_transform = use_l2_instead_of_per_transform
        self.negative_sampling_module = negative_sampling_module
        # train_mode in [0.0, 1.0]: 0.0 => pure classification, 1.0 => pure regression
        self.train_mode = float(train_mode)
 
        self.reset_head()
        self.clamp = clamp

        self.target_param_form = target_param_form
        self.use_mse = use_mse
        self.norm_constraint_weight = norm_constraint_weight

    def _freeze_batchnorm(self, module):
        for m in module.modules():
            if isinstance(m, torch.nn.modules.batchnorm._BatchNorm):
                m.eval()  # use running stats
                m.track_running_stats = False  # stop updating running_mean / running_var

    def reset_head(self):
        """
        Reset the head of the model regression networks.
        This is useful for reinitializing the model after loading a checkpoint.
        """
        # Reinitialize the regression network
        nn.init.normal_(self.regression_net.weight, 0, 0.01)
        with torch.no_grad():
            identity_params = self.transformation_problem.get_identity_parameters()
            # Ensure it’s the same shape as the bias
            identity_params = identity_params.view_as(self.regression_net.bias)
            # Sample uniformly from [identity_params - 0.1, identity_params + 0.1]
            self.regression_net.bias.copy_(
                identity_params
            )

    def _set_mode_except_lstm(self, module, train: bool):
        for name, child in module.named_children():
            # Skip LSTMs (they behave differently and do not use running stats)
            if isinstance(child, torch.nn.LSTM):
                continue

            # Set mode on BatchNorm, Conv, Linear, etc.
            child.train(train)

            # Recurse
            self._set_mode_except_lstm(child, train)

    def on_train_start(self):
        if not self.train_main:
            self._set_mode_except_lstm(self.main_model, train=False)

    def on_train_epoch_start(self):
        if not self.train_main:
            self._set_mode_except_lstm(self.main_model, train=False)


    def forward(self, x,y=None):
        # 0. Apply pretransform if available
        with torch.no_grad():
            if self.pretransform is not None:
                with torch.no_grad():
                    x = self.pretransform(x)

        # 1. Get features from localization network
        loc_features = self.localization_net(x)
        loc_features = loc_features.flatten(1)  # Flatten to [batch_size, features]

        # 2. Map features to transformation parameters
        params = self.regression_net(loc_features)

        
        # 4. Correct parameters to be within bounds
        if self.clamp:
            params = self.transformation_problem.correct_param(params,reflect=False)

        # 5. Apply transformation to input using the TransformationProblem
        x_transformed = self.transformation_problem.transform(x, params)

        # 6. Apply main model to transformed input
        return self.main_model(x_transformed)

    def forward_with_loss(self, x,y):
        """
        Forward pass with regularization on the localization network.
        """
        # 0. Apply pretransform if available
        with torch.no_grad():
            if self.pretransform is not None:
                with torch.no_grad():
                    x = self.pretransform(x)

        # 1. Compute localization features and predicted params (call networks only once)
        loc_features = self.localization_net(x)
        loc_features = loc_features.flatten(1)
        params = self.regression_net(loc_features)

        # Regularization term (kept separate)
        if self.l2_weight > 0.0:
            if not self.use_l2_instead_of_per_transform:
                l2_reg = self.transformation_problem.boundary_violation(params).mean() * self.l2_weight
            else:
                l2_reg = self.l2_weight * torch.nn.functional.mse_loss(
                    params, self.transformation_problem.get_identity_parameters(batch_size=params.shape[0])
                )
        else:
            l2_reg = torch.tensor(0.0, device=params.device)
        if self.norm_constraint_weight > 0.0:
            l2_reg+= self.norm_constraint_weight * self.transformation_problem.normalization_violation(params).mean()


        if self.clamp:
            params = self.transformation_problem.correct_param(params,reflect=False)

        if self.train_mode < 1.0:
            # Apply transformation and forward through main model/conf_module once
            x_transformed = self.transformation_problem.transform(x, params)

            if self.conf_module is None:
                logits = self.main_model(x_transformed)
                cls_loss = F.cross_entropy(logits, y)
            else:
                conf, logits = self.conf_module(x_transformed, y=y)
                cls_loss = (-conf).mean(0)
        else:
            # Skip main model, set results to None or zero
            logits = None
            cls_loss = torch.tensor(0.0, device=params.device)

        # Return logits, classification loss, l2 regularization term and predicted params
        return logits, cls_loss, l2_reg, params

    def transform_input(self, x):
        """
        Apply the regression_net prediction to x and return the transformed input.
        """
        # 1. optional pretransform
        if self.pretransform is not None:
            with torch.no_grad():
                x = self.pretransform(x)

        # 2. predict params
        loc = self.localization_net(x).flatten(1)
        params = self.regression_net(loc)

        # 3. optional clamp
        if self.clamp:
            params = self.transformation_problem.correct_param(params,reflect=False)

        # 4. Apply transformation using the TransformationProblem
        return self.transformation_problem.transform(x, params)

    def regress_target(self, x, target_params,use_mse=True):
        """
        Predict transformation parameters for x and compute MSE loss against target_params.
        """
        # NOTE: changed signature/behavior: accepts already-predicted params and target_params
        # (keeps networks from being called twice). Here `x` is actually the predicted params.
        predicted_params = x
        if use_mse or self.target_param_form in ['matrix','matrix_inverted']:
            T_p = self.transformation_problem(predicted_params)
            if self.target_param_form == 'matrix':
                T_t = target_params.detach()
            elif self.target_param_form == 'matrix_inverted':
                #make to float 32 if smaller
                orig_dtype = target_params.dtype
                if target_params.dtype in [torch.float16, torch.bfloat16]:
                    target_params = target_params.float()
                T_t = torch.inverse(target_params).detach()
                if orig_dtype in [torch.float16, torch.bfloat16]:
                    T_t = T_t.to(orig_dtype)
            else:
                T_t = self.transformation_problem(target_params).detach()
            reg_loss = F.mse_loss(T_p, T_t)

        else:
            reg_loss = (self.transformation_problem.distance(predicted_params, target_params) ** 2).mean(dim=0)

        # clamp won't change the loss here, but keep behavior consistent if needed
        if self.clamp:
            _ = self.transformation_problem.correct_param(predicted_params, reflect=False)

        return reg_loss

    def training_step(self, batch, batch_idx):
        # accept batches of (x, y) or (x, true_params, y)
        if len(batch) == 3:
            x, true_params, y = batch
        elif len(batch) == 2 and type(batch[0]) is tuple:
            x,y =batch[0]
            true_params = batch[1]
        elif len(batch) == 2:
            x, y = batch
            true_params = None
        else:
            raise ValueError("Training batch must contain either 2 or 3 elements (x, y, [true_params]).")

        # negative sampling is expected to operate on (x, y)
        with torch.no_grad():
            if self.negative_sampling_module is not None:
                zw= self.negative_sampling_module((x, y))
                if type(zw[0]) is tuple:
                    x,y=zw[0]
                    true_params=zw[1]
                else:
                    x,y=zw
            if true_params is None and self.train_mode > 0.0:
                raise ValueError("true_params required for regression mode when train_mode > 0.0.")

        logits, cls_loss, l2_reg, params = self.forward_with_loss(x, y)

        if logits is not None:
            preds = torch.argmax(logits, dim=1)
            acc = (preds == y).float().mean()
            self.log("train_acc", acc, prog_bar=True)



        # compute regression loss only if requested by train_mode
        if self.train_mode > 0.0:
            if true_params is None:
                raise ValueError("true_params required for regression mode when train_mode > 0.0.")
            reg_loss = self.regress_target(params, true_params, use_mse=self.use_mse)
        else:
            reg_loss = torch.tensor(0.0, device=cls_loss.device)


        main_loss = (1.0 - self.train_mode) * cls_loss + self.train_mode * reg_loss
        self.log("train_loss", main_loss, prog_bar=True)
        self.log("train_reg", l2_reg, prog_bar=True)
        if self.train_mode > 0.0:
            self.log("train_regression_loss", reg_loss, prog_bar=False)
        return main_loss + l2_reg
    @torch.no_grad()
    def validation_step(self, batch, batch_idx):
        # accept batches of (x, y) or (x, true_params, y)
        if len(batch) == 3:
            x, true_params, y = batch
        elif len(batch) == 2 and type(batch[0]) is tuple:
            x,y =batch[0]
            true_params = batch[1]
        elif len(batch) == 2:
            x, y = batch
            true_params = None
        else:
            raise ValueError("Training batch must contain either 2 or 3 elements (x, y, [true_params]).")

        # negative sampling is expected to operate on (x, y)
        if self.negative_sampling_module is not None and False: #never sample val set to not add randomness
            zw= self.negative_sampling_module((x, y))
            if type(zw[0]) is tuple:
                x,y=zw[0]
                true_params=zw[1]
            else:
                x,y=zw

        logits, cls_loss, l2_reg, params = self.forward_with_loss(x, y)

        if self.train_mode > 0.0 and true_params is not None:
            if true_params is None:
                raise ValueError("true_params required for regression mode when train_mode > 0.0.")
            reg_loss = self.regress_target(params, true_params)
        else:
            reg_loss = torch.tensor(0.0, device=cls_loss.device)

        main_loss = (1.0 - self.train_mode) * cls_loss + self.train_mode * reg_loss
        if logits is None:
            x_transformed = self.transformation_problem.transform(x, params)
            logits = self.main_model(x_transformed)


        preds = torch.argmax(logits, dim=1)
        acc = (preds == y).float().mean()
        self.log("val_loss", main_loss, prog_bar=True)
        self.log("val_reg", l2_reg, prog_bar=True)
        self.log("val_acc", acc, prog_bar=True)
        if self.train_mode > 0.0:
            self.log("val_regression_loss", reg_loss, prog_bar=False)
        return main_loss + l2_reg

    def configure_optimizers(self):
        if self.train_main:
            raise NotImplementedError("Optimizing main model not implemented yet.")
            opt = self.optimizer_class(self.localization_net.parameters(), **self.optimizer_params)
            opt.add_param_group({"params": self.regression_net.parameters()})
            opt.add_param_group({"params": self.main_model.parameters()})
        else:
            # Only optimize localization and regression networks
            opt = self.optimizer_class(self.localization_net.parameters(), **self.optimizer_params)
            opt.add_param_group({"params": self.regression_net.parameters()})

        if self.lr_scheduler is not None:
            scheduler = self.lr_scheduler(opt, **(self.lr_scheduler_params or {}))
            if self.lr_config is not None:
                self.lr_config["scheduler"] = scheduler
            else:
                self.lr_config = {"scheduler": scheduler, "interval": "epoch", "monitor": "val_loss", "frequency": 1, "strict": True, "name": None}

            return {"optimizer": opt, "lr_scheduler": self.lr_config}
        else:
            return opt
