from typing import Literal
import torch
import numpy as np
from scipy.spatial import Delaunay
from utils.transformation_problem import TransformationProblem


class SHGO:
    """
    Random search plus refinment based somewhat on (SHGO)-style optimizer from pytorch.
    Untested mostly generated by translating the scipy implementation using copilot have to change this if it works.
    1. Draw N global samples via transformation_problem.initial_param
    2. Select candidates using either:
       a. Top-K selection (original method)
       b. Delaunay triangulation-based topological analysis
       c. Simplicial approach (1D) for finding local minima
       d. k-NN graph-based approximation of Delaunay minimizer selection
    3. Refine each of the candidates by local gradient descent
    """

    def __init__(
            self,
            initial_samples: int = 100,
            local_runs: int = 4,
            local_max_steps: int = 10,
            local_opt_class=torch.optim.Adam,
            local_opt_kwargs=None,
            selection_method:Literal['topk','delaunay','simplicial','knn']='topk',
            acceptance_criterion: Literal['always', 'step', 'final'] = 'step',
            project_param: bool = True,  # NEW
            sigma: float = 0.0,  # bandwidth for Gaussian smoothing of errors,
            include_zero_always: bool = False,  # NEW
    ):
        self.initial_samples = initial_samples
        self.local_runs = local_runs
        self.local_max_steps = local_max_steps
        self.local_opt_class = local_opt_class
        self.local_opt_kwargs = local_opt_kwargs or {"lr": 1e-1}
        self.selection_method = selection_method
        self.acceptance_criterion = acceptance_criterion
        self.project_param = project_param
        self.sigma = sigma
        self.include_zero_always = include_zero_always


    def optimize(self, transformation_problem: TransformationProblem, x,y=None, verbose=False):
        with torch.no_grad():
            batch_size = x.shape[0]
            # 1) global sampling
            if self.include_zero_always:
                # Get one fewer so we can prepend zero later
                all_params = transformation_problem.initial_param(
                    batch_size, self.initial_samples - 1
                )

                # Build a zero tensor matching the trailing dimensions
                zero_shape = (batch_size, 1) + tuple(all_params.shape[2:])
                zero_param = torch.zeros(
                    zero_shape, device=all_params.device, dtype=all_params.dtype
                )

                # Concatenate along the sample dimension
                all_params = torch.cat([zero_param, all_params], dim=1)
            else:
                all_params = transformation_problem.initial_param(
                    batch_size, self.initial_samples
                )


            dim = all_params.shape[-1]
            all_params = all_params.view(-1, dim)
            x_rep = x.repeat_interleave(self.initial_samples, dim=0)
            if y is not None:
                y_rep = y.repeat_interleave(self.initial_samples, dim=0)
            else:
                y_rep = None


            all_err, all_other = transformation_problem.calculate_error(x_rep, all_params, y=y_rep)
            # reshape to (batch, samples, ...)
            all_err = all_err.view(batch_size, self.initial_samples)
            all_other = all_other.view(batch_size, self.initial_samples, -1)
            all_params = all_params.view(batch_size, self.initial_samples, dim)

            if self.sigma > 0:
                all_err = self._smooth_errors(all_params, all_err, sigma=self.sigma)

            # 2) select candidates based on chosen method
            best_params, best_err, best_other = self._select_candidates(
                all_params, all_err, all_other, batch_size, dim
            )

            # flatten for local search
            flat_params = best_params.view(-1, dim).clone().detach().requires_grad_(True)
            x_rep2 = x.repeat_interleave(best_params.shape[1], dim=0)
            y_rep2 = y.repeat_interleave(best_params.shape[1], dim=0) if y is not None else None

            # 3) parallel local gradient descent
            if self.acceptance_criterion == 'step':
                # Keep track of the best parameters found so far during local search
                best_step_params = flat_params.clone()
                best_step_err = best_err.view(-1)
                best_step_other = best_other.view(-1, best_other.shape[-1])

            with torch.enable_grad():
                optimizer = self.local_opt_class([flat_params], **self.local_opt_kwargs)
                for step in range(self.local_max_steps):
                    optimizer.zero_grad()
                    # It's the params *before* the step that correspond to `err`
                    params_before_step = flat_params.clone()
                    err, other = transformation_problem.calculate_error(x_rep2, flat_params, y=y_rep2)
                    loss = err.mean()
                    loss.backward()
                    optimizer.step()
                    with torch.no_grad():
                        if self.project_param:
                            flat_params.data = transformation_problem.correct_param(flat_params).data
                        else:
                            flat_params.data = transformation_problem.normalize(flat_params).data

                        if self.acceptance_criterion == 'step':
                            improved_mask = err < best_step_err
                            best_step_params = torch.where(improved_mask.unsqueeze(-1), params_before_step, best_step_params)
                            best_step_err = torch.where(improved_mask, err, best_step_err)
                            best_step_other = torch.where(improved_mask.unsqueeze(-1), other, best_step_other)

            if self.local_max_steps>0:
                # final evaluation
                with torch.no_grad():
                    # After the loop, flat_params is at the final position. Evaluate it.
                    final_err, final_other = transformation_problem.calculate_error(x_rep2, flat_params, y=y_rep2)

                    if self.acceptance_criterion == 'step':
                        # Compare the final position with the best-so-far from previous steps
                        improved_mask = final_err < best_step_err
                        final_params_flat = torch.where(improved_mask.unsqueeze(-1), flat_params, best_step_params)
                        final_err = torch.where(improved_mask, final_err, best_step_err)
                        final_other = torch.where(improved_mask.unsqueeze(-1), final_other, best_step_other)
                    else: # 'always' or 'final'
                        final_params_flat = flat_params
                        # final_err and final_other are already set from the evaluation above
            else:
                final_params_flat = flat_params.detach()
                final_err = best_err.view(-1).detach()
                final_other = best_other.view(-1, best_other.shape[-1]).detach()

            # reshape back to (batch, runs, ...)
            n_candidates = best_params.shape[1]
            final_params = final_params_flat.view(batch_size, n_candidates, dim)
            final_err = final_err.view(batch_size, n_candidates)
            final_other = final_other.view(batch_size, n_candidates, -1)

            # Accept only improvements if option enabled
            if self.acceptance_criterion == 'final':
                improved = final_err < best_err
                # Where not improved, revert to original (random sample) values
                final_params = torch.where(improved.unsqueeze(-1), final_params, best_params)
                final_err = torch.where(improved, final_err, best_err)
                final_other = torch.where(improved.unsqueeze(-1), final_other, best_other)

            # consolidate best per sample
            return transformation_problem.consolidate(x, final_params, final_err, final_other)

    def _smooth_errors(self, all_params, all_err, sigma=0.1):
        """
        Smooth error values with Gaussian kernel regression in parameter space.
        - all_params: (batch, n, dim)
        - all_err: (batch, n)
        - sigma: bandwidth of Gaussian kernel. Larger = more smoothing.
        """

        b, n, d = all_params.shape

        # pairwise distances in parameter space (batch, n, n)
        dists = torch.cdist(all_params, all_params)

        # Gaussian kernel weights
        weights = torch.exp(-0.5 * (dists / sigma) ** 2)
        weights = weights / (weights.sum(dim=-1, keepdim=True) + 1e-9)

        # weighted average of neighbor errors
        smoothed_err = torch.bmm(weights, all_err.unsqueeze(-1)).squeeze(-1)
        return smoothed_err


    def _select_candidates(self, all_params, all_err, all_other, batch_size, dim):
        """Select candidates based on the chosen selection method"""
        if self.selection_method == 'topk':
            return self._select_topk(all_params, all_err, all_other, batch_size, dim)
        elif self.selection_method == 'delaunay':
            return self._select_delaunay(all_params, all_err, all_other, batch_size, dim)
        elif self.selection_method == 'simplicial':
            return self._select_simplicial(all_params, all_err, all_other, batch_size, dim)
        elif self.selection_method == 'knn':
            return self._select_knn(all_params, all_err, all_other, batch_size, dim)
        else:
            raise ValueError(f"Unknown selection method: {self.selection_method}")

    def _select_knn(self, all_params, all_err, all_other, batch_size, dim):
        device = all_params.device
        b, n, d = all_params.shape
        runs = min(self.local_runs, n)

        k = min(max(2 * dim, 12), n - 1) if n > 1 else 0
        if k == 0:
            idx = torch.zeros((b, 1), dtype=torch.long, device=device)
            best_params = torch.gather(all_params, 1, idx.unsqueeze(-1).expand(-1, -1, d))
            best_err = torch.gather(all_err, 1, idx)
            best_other = torch.gather(all_other, 1, idx.unsqueeze(-1).expand(-1, -1, all_other.shape[-1]))
            return best_params, best_err, best_other

        # 1) Pairwise distances
        dists = torch.cdist(all_params, all_params)
        knn_idx = torch.topk(dists, k=k + 1, largest=False).indices[..., 1:]  # (b, n, k)

        # 2) Compare errors with neighbors
        neigh_errs = torch.gather(all_err.unsqueeze(2).expand(-1, -1, k), 1, knn_idx)
        is_min = (all_err.unsqueeze(2) < neigh_errs).all(dim=2)  # (b, n)

        # 3) Mask non-minimizers with +inf
        masked_errs = all_err.clone()
        masked_errs[~is_min] = float("inf")

        # 4) Select minimizers (some slots may still be inf)
        topk_min = torch.topk(masked_errs, runs, largest=False)
        chosen_idx = topk_min.indices  # (b, runs)

        # 5) Ensure we don’t duplicate: fill missing slots only from non-minimizers
        n_mins = is_min.sum(dim=1)  # number of minimizers per batch
        need_fill = runs - torch.minimum(n_mins, torch.tensor(runs, device=device))

        if need_fill.any():
            # For batches with fewer minimizers, compute global-best **excluding minimizers**
            not_min = ~is_min  # (b, n)
            # set minimizer errors to inf so they won’t be picked again
            global_errs = all_err.clone()
            global_errs[~not_min] = float("inf")

            global_best = torch.topk(global_errs, runs, largest=False).indices  # (b, runs)

            # Fill slots that had inf with non-minimizer bests
            fill_mask = torch.isinf(torch.gather(masked_errs, 1, chosen_idx))  # (b, runs)
            chosen_idx = torch.where(fill_mask, global_best, chosen_idx)

        # 6) Gather results
        best_params = torch.gather(all_params, 1, chosen_idx.unsqueeze(-1).expand(-1, -1, d))
        best_err = torch.gather(all_err, 1, chosen_idx)
        best_other = torch.gather(all_other, 1, chosen_idx.unsqueeze(-1).expand(-1, -1, all_other.shape[-1]))

        return best_params, best_err, best_other


    def _select_topk(self, all_params, all_err, all_other, batch_size, dim):
        """Original topK selection method"""
        topk = torch.topk(all_err, min(self.local_runs, all_err.shape[1]), largest=False)
        idx = topk.indices  # (batch, local_runs)

        # gather best params and data
        best_params = torch.gather(
            all_params, 1, idx.unsqueeze(-1).expand(-1, -1, dim)
        )
        best_other = torch.gather(
            all_other, 1, idx.unsqueeze(-1).expand(-1, -1, all_other.shape[-1])
        )
        best_err = torch.gather(all_err, 1, idx)

        return best_params, best_err, best_other

    #based on scipy implementation translated copilot todo make parallel?
    def _select_delaunay(self, all_params, all_err, all_other, batch_size, dim):
        """
        Delaunay triangulation-based selection method.
        Identifies points that are local minima in the Delaunay graph.
        """
        all_minimizers = []
        all_minimizer_params = []
        all_minimizer_errs = []
        all_minimizer_others = []

        for b in range(batch_size):
            # Convert to numpy for Delaunay triangulation
            params_np = all_params[b].detach().cpu().numpy()
            err_np = all_err[b].detach().cpu().numpy()

            # Skip if we don't have enough points for triangulation
            if params_np.shape[0] <= dim + 1:
                # Fall back to topk for this batch element
                topk = torch.topk(all_err[b], min(self.local_runs, all_err[b].shape[0]), largest=False)
                minimizers = topk.indices
            else:
                try:
                    # Create Delaunay triangulation
                    tri = Delaunay(params_np)

                    # Find minimizers (points that are lower than all neighbors)
                    minimizers = []
                    for i in range(len(params_np)):
                        # Get neighbors in Delaunay graph
                        neighbors = self._find_neighbors_delaunay(i, tri)

                        # Check if point is lower than all neighbors
                        is_minimizer = True
                        for n in neighbors:
                            if err_np[i] >= err_np[n]:
                                is_minimizer = False
                                break

                        if is_minimizer:
                            minimizers.append(i)

                    # If no minimizers found or too many, fall back to topk
                    if not minimizers or len(minimizers) > self.local_runs * 2:
                        topk = torch.topk(all_err[b], min(self.local_runs, all_err[b].shape[0]), largest=False)
                        minimizers = topk.indices.cpu().numpy()

                    # Limit to top self.local_runs minimizers
                    if len(minimizers) > self.local_runs:
                        minimizer_errs = err_np[minimizers]
                        top_indices = np.argsort(minimizer_errs)[:self.local_runs]
                        minimizers = [minimizers[i] for i in top_indices]
                except Exception as e:
                    # Fall back to topk if triangulation fails
                    print(f"Delaunay triangulation failed: {e}. Falling back to topk.")
                    topk = torch.topk(all_err[b], min(self.local_runs, all_err[b].shape[0]), largest=False)
                    minimizers = topk.indices.cpu().numpy()

            # Store minimizers for this batch
            minimizers = torch.tensor(minimizers, device=all_params.device)
            all_minimizers.append(minimizers)

            # Extract parameters, errors, and other data for minimizers
            if len(minimizers) > 0:
                batch_params = all_params[b][minimizers]
                batch_errs = all_err[b][minimizers]
                batch_others = all_other[b][minimizers]
            else:
                # If no minimizers, fall back to best point
                best_idx = torch.argmin(all_err[b])
                batch_params = all_params[b][best_idx:best_idx + 1]
                batch_errs = all_err[b][best_idx:best_idx + 1]
                batch_others = all_other[b][best_idx:best_idx + 1]

            all_minimizer_params.append(batch_params)
            all_minimizer_errs.append(batch_errs)
            all_minimizer_others.append(batch_others)

        # Pad sequences to same length
        max_minimizers = max(len(m) for m in all_minimizer_params)
        padded_params = []
        padded_errs = []
        padded_others = []

        for params, errs, others in zip(all_minimizer_params, all_minimizer_errs, all_minimizer_others):
            if len(params) < max_minimizers:
                # Padding needed - replicate the first minimizer
                n_pad = max_minimizers - len(params)
                padded_params.append(torch.cat([params, params[:1].repeat(n_pad, 1)], dim=0))
                padded_errs.append(torch.cat([errs, errs[:1].repeat(n_pad)], dim=0))
                padded_others.append(torch.cat([others, others[:1].repeat(n_pad, 1)], dim=0))
            else:
                padded_params.append(params)
                padded_errs.append(errs)
                padded_others.append(others)

        # Stack into batch tensors
        best_params = torch.stack(padded_params, dim=0)
        best_err = torch.stack(padded_errs, dim=0)
        best_other = torch.stack(padded_others, dim=0)

        return best_params, best_err, best_other

    def _select_simplicial(self, all_params, all_err, all_other, batch_size, dim):
        """
        Simplicial approach (1D) for finding local minima.
        For each dimension, identifies points that are local minima along that axis.
        """
        all_minimizers = []
        all_minimizer_params = []
        all_minimizer_errs = []
        all_minimizer_others = []

        for b in range(batch_size):
            params = all_params[b]
            errs = all_err[b]

            # Start with all points as potential minimizers
            potential_minimizers = torch.ones(params.shape[0], dtype=torch.bool, device=params.device)

            # For each dimension, check if point is a local minimum along that axis
            for d in range(dim):
                # Sort points along this dimension
                _, sort_idx = torch.sort(params[:, d])
                sorted_errs = errs[sort_idx]

                # Compute forward and backward differences
                fwd_diff = torch.diff(sorted_errs)
                bwd_diff = torch.diff(sorted_errs.flip(0)).flip(0)

                # Points are minimizers if they're lower than neighbors in both directions
                # Handle edge cases for first and last points
                is_min_d = torch.zeros_like(potential_minimizers)

                # First point is a minimizer if it's lower than the next point
                if len(sorted_errs) > 1:
                    is_min_d[sort_idx[0]] = sorted_errs[0] < sorted_errs[1]

                    # Last point is a minimizer if it's lower than the previous point
                    is_min_d[sort_idx[-1]] = sorted_errs[-1] < sorted_errs[-2]

                # Interior points
                if len(sorted_errs) > 2:
                    for i in range(1, len(sorted_errs) - 1):
                        is_min_d[sort_idx[i]] = (sorted_errs[i] < sorted_errs[i - 1]) and (
                                    sorted_errs[i] < sorted_errs[i + 1])

                # Update potential minimizers (must be min in all dimensions)
                potential_minimizers = potential_minimizers & is_min_d

            # Get indices of minimizers
            minimizers = torch.where(potential_minimizers)[0]

            # If no minimizers found or too many, fall back to topk
            if len(minimizers) == 0 or len(minimizers) > self.local_runs * 2:
                topk = torch.topk(errs, min(self.local_runs, errs.shape[0]), largest=False)
                minimizers = topk.indices

            # Limit to top self.local_runs minimizers
            if len(minimizers) > self.local_runs:
                minimizer_errs = errs[minimizers]
                topk = torch.topk(minimizer_errs, self.local_runs, largest=False)
                minimizers = minimizers[topk.indices]

            # Store minimizers for this batch
            all_minimizers.append(minimizers)

            # Extract parameters, errors, and other data for minimizers
            if len(minimizers) > 0:
                batch_params = params[minimizers]
                batch_errs = errs[minimizers]
                batch_others = all_other[b][minimizers]
            else:
                # If no minimizers, fall back to best point
                best_idx = torch.argmin(errs)
                batch_params = params[best_idx:best_idx + 1]
                batch_errs = errs[best_idx:best_idx + 1]
                batch_others = all_other[b][best_idx:best_idx + 1]

            all_minimizer_params.append(batch_params)
            all_minimizer_errs.append(batch_errs)
            all_minimizer_others.append(batch_others)

        # Pad sequences to same length
        max_minimizers = max(len(m) for m in all_minimizer_params)
        padded_params = []
        padded_errs = []
        padded_others = []

        for params, errs, others in zip(all_minimizer_params, all_minimizer_errs, all_minimizer_others):
            if len(params) < max_minimizers:
                # Padding needed - replicate the first minimizer
                n_pad = max_minimizers - len(params)
                padded_params.append(torch.cat([params, params[:1].repeat(n_pad, 1)], dim=0))
                padded_errs.append(torch.cat([errs, errs[:1].repeat(n_pad)], dim=0))
                padded_others.append(torch.cat([others, others[:1].repeat(n_pad, 1)], dim=0))
            else:
                padded_params.append(params)
                padded_errs.append(errs)
                padded_others.append(others)

        # Stack into batch tensors
        best_params = torch.stack(padded_params, dim=0)
        best_err = torch.stack(padded_errs, dim=0)
        best_other = torch.stack(padded_others, dim=0)

        return best_params, best_err, best_other

    @staticmethod
    def _find_neighbors_delaunay(pindex, triang):
        """
        Returns the indexes of points connected to pindex on the Delaunay triangulation.
        Similar to the function in the SciPy SHGO implementation.
        """
        return triang.vertex_neighbor_vertices[1][
               triang.vertex_neighbor_vertices[0][pindex]:
               triang.vertex_neighbor_vertices[0][pindex + 1]]